networks:
  production:
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:17.4.5
    container_name: teleport
    restart: unless-stopped
    networks:
      - production
    ports:
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lig/teleport
      - ./logs:/var/log/teleport
