version: v3
teleport:
  nodename: "teleport-node"
  data_dir: "/var/lib/teleport"
  log:
    output: stdout
    severity: INFO
    format:
      output: text
auth_service:
  enabled: true
  cluster_name: "example.com"
  #listen_addr: "0.0.0.0:3025"
  #proxy_listener_mode: multiplex

ssh_service:
  enabled: false

proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080

app_service:
  enabled: false
